---
- name: Ensure CouchDB config directory exists
  ansible.builtin.file:
    path: "{{ couchdb_home }}/config"
    state: directory
    owner: root
    group: root
    mode: "0755"


- name: Deploy CouchDB local.ini
  ansible.builtin.template:
    src: local.ini.j2
    dest: "{{ couchdb_home }}/config/local.ini"
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart CouchDB