---
- name: workers setup
  hosts: k8s-worker-1
  become: yes
  gather_facts: yes
  vars_files:
      - /app/inventory/group_vars/workers.yaml

  roles:
    # - ufw
    # - fail2ban
    - docker
    # - nginx

# ---
# - name: Install and configure Nginx
#   hosts: control_plane
#   become: yes
#   tasks:
    # Nginx
    # - name: Include Nginx tasks
    #   include_tasks: /app/playbooks/setup/nginx.yml    
    # # Bind9
    # - name: Include Bind9 tasks
    #   include_tasks: /app/playbooks/setup/bind9.yml  
    # # UFW
    # - name: Include UFW tasks
    #   include_tasks: /app/playbooks/setup/ufw.yml  
    # # Fail2Ban
    # - name: Include Fail2Ban tasks
    #   include_tasks: /app/playbooks/setup/fail2ban.yml
# Docker
# -  import_playbook: /app/playbooks/setup/docker.yml      

# DBs
# - name: Install and configure Nginx
  # hosts: dbservers
  # become: yes
  # tasks:
  # Mongodb
    # - name: Include Mongodb tasks
    #   include_tasks: /app/playbooks/setup/mongodb.yml 
  # CouchDB
    # - name: Include CouchDB tasks
    #   include_tasks: /app/playbooks/setup/couchdb.yml      


# Fast syntax check only
# ansible-playbook -i /app/inventory/contabo.yml /app/playbooks/2_setup.yml --ask-become-pass --syntax-check

# If syntax ok → try a dry run
# ansible-playbook -i /app/inventory/contabo.yml /app/playbooks/2_setup.yml --ask-become-pass --check --diff 

# If everything looks good → real run
# ansible-playbook -i /app/inventory/contabo.yml /app/playbooks/2_setup.yml --ask-become-pass --ask-vault-pass --extra-vars "@/app/secrets/secrets.yml"

# Debugging
# ansible k8s-worker-1 -i /app/inventory/contabo.yml -m debug -a "var=ansible_host" 
# ansible k8s-worker-1 -i /app/inventory/contabo.yml -m debug -a "var=ansible_user"
