---
- name: Deploy Nginx configurations for multiple domains
  hosts: userver
  become: yes
  vars:
    domains:
      # - name: gallusgarten.de
        # src: /app/server/nginx/gallusgarten.de.conf
      # - name: api.gallusgarten.de
      #   src: /app/server/nginx/api.gallusgarten.de.conf        
      # - name: seointro.de
      #   src: /app/server/nginx/seointro.de.conf
      # - name: couchdb.seointro.de
      #   src: /app/server/nginx/couchdb.seointro.de.conf   
      - name: almasaralabyad.com
        src: /app/server/nginx/almasaralabyad.com.conf                   

  tasks:
    - name: Copy Nginx configuration to sites-available
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "/etc/nginx/sites-available/{{ item.name }}.conf"
        owner: root
        group: root
        mode: '0644'
      loop: "{{ domains }}"

    - name: Create symlink to sites-enabled
      ansible.builtin.file:
        src: "/etc/nginx/sites-available/{{ item.name }}.conf"
        dest: "/etc/nginx/sites-enabled/{{ item.name }}.conf"
        state: link
      loop: "{{ domains }}"

    - name: Test Nginx configuration
      ansible.builtin.command: nginx -t
      register: nginx_test
      ignore_errors: yes

    - name: Fail if Nginx configuration test failed
      ansible.builtin.fail:
        msg: "Nginx configuration test failed: {{ nginx_test.stderr }}"
      when: nginx_test.rc != 0

    - name: Reload Nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded


# Fast syntax check only
# ansible-playbook -i /app/inventory/contabo.yml /app/playbooks/3_deploy.yml --ask-become-pass --syntax-check

# If syntax ok → try a dry run
# ansible-playbook -i /app/inventory/contabo.yml /app/playbooks/3_deploy.yml --ask-become-pass --check --diff 

# If everything looks good → real run
# ansible-playbook -i /app/inventory/contabo.yml /app/playbooks/3_deploy.yml --ask-become-pass


