# ansible\playbooks\phase-1.yml
---
- name: Phase 1 - Kubernetes Bootstrap
  hosts: all
  become: true
  vars_files:
      - /app/inventory/group_vars/all.yml
  roles:
    - kubeadm

# Fast syntax check only
# ansible-playbook -i /app/inventory/contabo.yml /app/playbooks/phase-0.yml --syntax-check

# If syntax ok → try a dry run
# ansible-playbook -i /app/inventory/contabo.yml /app/playbooks/phase-0.yml --check --diff

# If everything looks good → real run
# ansible-playbook -i /app/inventory/contabo.yml /app/playbooks/phase-0.yml
