- name: Add Kubernetes apt key
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/Release.key
    dest: /usr/share/keyrings/kubernetes-archive-keyring.gpg

- name: Add Kubernetes apt repo
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/ /"
    state: present

- name: Install kubeadm, kubelet, kubectl
  ansible.builtin.apt:
    name:
      - kubeadm
      - kubelet
      - kubectl
    state: present
    update_cache: yes

- name: Hold Kubernetes packages
  ansible.builtin.apt:
    name:
      - kubeadm
      - kubelet
      - kubectl
    state: present
    mark_hold: yes
