---
- name: Update package lists
  apt:
    update_cache: yes

- name: Install required dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - libmozjs-68-0
    - libicu66
    - libssl1.1

- name: Install CouchDB
  apt:
    name: couchdb
    state: present
    force_apt_get: yes

- name: Fix broken packages (if necessary)
  command: dpkg --configure -a
  when: result.rc != 0

- name: Restart CouchDB service
  service:
    name: couchdb
    state: restarted

- name: Check CouchDB service status
  command: systemctl status couchdb
  register: couchdb_status
  failed_when: "'failed' in couchdb_status.stdout"