---
- name: Install and configure Fail2Ban
  ansible.builtin.apt:
    name: fail2ban
    state: present
    update_cache: yes

- name: Start and enable Fail2Ban service
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: yes
# - name: Install and configure Fail2Ban
#   # hosts: all
#   become: yes
#   vars:
#     ssh_port: 22
#     maxretry: 5
#     bantime: 3600
#     findtime: 600
#   tasks:

#     - name: Ensure Fail2Ban is installed (Debian/Ubuntu)
#       apt:
#         name: fail2ban
#         state: present
#       when: ansible_os_family == 'Debian'

#     - name: Ensure Fail2Ban is installed (CentOS/RedHat)
#       yum:
#         name: fail2ban
#         state: present
#       when: ansible_os_family == 'RedHat'

#     - name: Create Fail2Ban configuration directory if not exists
#       file:
#         path: /etc/fail2ban/jail.d
#         state: directory
#         mode: '0755'

#     - name: Configure Fail2Ban for SSH
#       copy:
#         dest: /etc/fail2ban/jail.d/ssh.conf
#         content: |
#           [sshd]
#           enabled = true
#           port = {{ ssh_port }}
#           filter = sshd
#           logpath = /var/log/auth.log  # Use /var/log/secure for RedHat-based systems
#           maxretry = {{ maxretry }}
#           bantime = {{ bantime }}
#           findtime = {{ findtime }}
#       notify:
#         - Restart Fail2Ban

#     - name: Ensure Fail2Ban service is started and enabled
#       service:
#         name: fail2ban
#         state: started
#         enabled: yes

#   handlers:
#     - name: Restart Fail2Ban
#       service:
#         name: fail2ban
#         state: restarted
